alias wdir="cd /p/psg/swip/w/drathina/"
alias ddir="cd /p/psg/data/drathina"

#alias gtags="gtags -u"
alias tdev="tmux a -t dev"
alias tls="tmux ls"
alias vt="v -t "
alias alltags="gtags && cscope -Rb"
alias cs="cscope"
alias tdut="tmux a -t dut"
alias gd="git diff"
alias gpd="git --paginate diff"
